version: "3"

services:
  redis:
    image: "redis:alpine"
    expose:
      - "6379"

  django:
    build:
      context: ..
    volumes:
      - ..:/app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    environment:
      - DJANGO_PORT
    command: >
      sh -c "python3 /app/manage.py runserver 0.0.0.0:${DJANGO_PORT}"
